In [1]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('/home/khaledsultan/Desktop/final project data/Fantasy-Premier-League-master/data/cleaned_merged_seasons.csv',index_col=0,parse_dates=True)

/home/khaledsultan/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df.head()

,season_x,name,position,team_x,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,...,2.0,0.0,0,0,0,0,55,False,0,1
1,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,...,1.0,0.0,0,0,0,0,50,False,0,1
2,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,286,...,1.0,0.0,1,0,0,0,45,True,1,1
3,2016-17,Adam Lallana,MID,NaN,1,2,33,0,33.7,205,...,3.0,57.0,11,0,0,0,70,False,1,1
4,2016-17,Adrián San Miguel del Castillo,GK,NaN,0,0,16,0,0.0,450,...,2.0,0.0,2,0,0,0,50,False,0,1

In [4]:
df_22 = pd.read_csv('/home/khaledsultan/Desktop/final project data/Fantasy-Premier-League-master/data/2021-22/gws/merged_gw.csv',index_col=0,parse_dates=True)

In [5]:
df.season_x.dtype

dtype('O')

In [6]:
df_22

,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
name,,,,,,,,,,,,,,,,,,,,,
Eric Bailly,DEF,Man Utd,0.0,0,0,0,0,0.0,286,6,...,5,0.0,0,0,0,0,50,True,0,1
Keinan Davis,FWD,Aston Villa,0.4,0,0,0,0,0.0,49,8,...,3,0.0,0,0,0,0,45,False,0,1
Ayotomiwa Dele-Bashiru,MID,Watford,0.0,0,0,0,0,0.0,394,8,...,3,0.0,0,0,0,0,45,True,0,1
James Ward-Prowse,MID,Southampton,2.3,0,0,20,0,30.5,341,4,...,3,0.0,2,0,0,0,65,False,0,1
Bruno Miguel Borges Fernandes,MID,Man Utd,4.4,0,3,61,0,35.9,277,6,...,5,59.0,20,0,0,0,120,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wilfred Ndidi,MID,Leicester,3.3,0,0,13,0,2.0,216,26,...,1,2.0,2,-7608,9581,17189,50,False,0,3
Matt Ritchie,DEF,Newcastle,1.2,0,0,12,0,11.3,292,25,...,2,4.0,1,208,4934,4726,50,True,0,3
Nathan Redmond,MID,Southampton,1.2,0,0,4,0,23.3,336,25,...,2,0.0,1,-1164,403,1567,59,False,0,3
Mathew Ryan,GK,Brighton,0.0,0,0,0,0,0.0,65,22,...,0,0.0,0,-134,0,134,45,True,0,3
Ryan Fredericks,DEF,West Ham,0.8,0,0,0,0,0.0,415,28,...,2,0.0,0,-996,582,1578,45,True,0,3

In [7]:
 df_22.columns

Index(['position', 'team', 'xP', 'assists', 'bonus', 'bps', 'clean_sheets',
       'creativity', 'element', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'opponent_team',
       'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards',
       'round', 'saves', 'selected', 'team_a_score', 'team_h_score', 'threat',
       'total_points', 'transfers_balance', 'transfers_in', 'transfers_out',
       'value', 'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [8]:
df_22.reset_index(inplace=True)

In [9]:
df_22 = df_22.drop('xP',axis = 1)

In [10]:
df.rename(columns={'team_x':'team'}, inplace=True)

In [11]:
df = df.drop('opp_team_name',axis = 1)

In [12]:
df_22.columns

Index(['name', 'position', 'team', 'assists', 'bonus', 'bps', 'clean_sheets',
       'creativity', 'element', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'opponent_team',
       'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards',
       'round', 'saves', 'selected', 'team_a_score', 'team_h_score', 'threat',
       'total_points', 'transfers_balance', 'transfers_in', 'transfers_out',
       'value', 'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [13]:
df_22.shape

(1697, 35)

In [14]:
df_22.insert(0, 'season_x', '2021-22' )

In [15]:
df_22

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2021-22,Eric Bailly,DEF,Man Utd,0,0,0,0,0.0,286,...,5,0.0,0,0,0,0,50,True,0,1
1,2021-22,Keinan Davis,FWD,Aston Villa,0,0,0,0,0.0,49,...,3,0.0,0,0,0,0,45,False,0,1
2,2021-22,Ayotomiwa Dele-Bashiru,MID,Watford,0,0,0,0,0.0,394,...,3,0.0,0,0,0,0,45,True,0,1
3,2021-22,James Ward-Prowse,MID,Southampton,0,0,20,0,30.5,341,...,3,0.0,2,0,0,0,65,False,0,1
4,2021-22,Bruno Miguel Borges Fernandes,MID,Man Utd,0,3,61,0,35.9,277,...,5,59.0,20,0,0,0,120,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1692,2021-22,Wilfred Ndidi,MID,Leicester,0,0,13,0,2.0,216,...,1,2.0,2,-7608,9581,17189,50,False,0,3
1693,2021-22,Matt Ritchie,DEF,Newcastle,0,0,12,0,11.3,292,...,2,4.0,1,208,4934,4726,50,True,0,3
1694,2021-22,Nathan Redmond,MID,Southampton,0,0,4,0,23.3,336,...,2,0.0,1,-1164,403,1567,59,False,0,3
1695,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,65,...,0,0.0,0,-134,0,134,45,True,0,3
1696,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,415,...,2,0.0,0,-996,582,1578,45,True,0,3

In [16]:
df

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,...,2.0,0.0,0,0,0,0,55,False,0,1
1,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,...,1.0,0.0,0,0,0,0,50,False,0,1
2,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,286,...,1.0,0.0,1,0,0,0,45,True,1,1
3,2016-17,Adam Lallana,MID,NaN,1,2,33,0,33.7,205,...,3.0,57.0,11,0,0,0,70,False,1,1
4,2016-17,Adrián San Miguel del Castillo,GK,NaN,0,0,16,0,0.0,450,...,2.0,0.0,2,0,0,0,50,False,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69019,2020-21,Aaron Ramsdale,GK,Sheffield Utd,0,2,30,1,10.0,483,...,1.0,0.0,9,13618,17381,3763,46,True,0,38
69020,2020-21,Adrien Silva,MID,Leicester,0,0,0,0,0.0,220,...,2.0,0.0,0,-16,0,16,44,True,0,38
69021,2020-21,Sidnei Tavares,MID,Leicester,0,0,0,0,0.0,676,...,2.0,0.0,0,32,60,28,44,True,0,38
69022,2020-21,Kalvin Phillips,MID,Leeds,0,0,17,0,12.8,204,...,3.0,8.0,6,210,789,579,49,True,1,38
69023,2020-21,Raphael Dias Belloli,MID,Leeds,1,0,24,0,60.2,570,...,3.0,31.0,5,124979,142069,17090,56,True,0,38

In [17]:
df.columns

Index(['season_x', 'name', 'position', 'team', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'fixture', 'goals_conceded',
       'goals_scored', 'ict_index', 'influence', 'kickoff_time', 'minutes',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'red_cards', 'round', 'saves', 'selected', 'team_a_score',
       'team_h_score', 'threat', 'total_points', 'transfers_balance',
       'transfers_in', 'transfers_out', 'value', 'was_home', 'yellow_cards',
       'GW'],
      dtype='object')

In [18]:
df.shape

(69024, 36)

In [19]:
frames = [df, df_22]

result = pd.concat(frames)

In [20]:
result

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,...,2.0,0.0,0,0,0,0,55,False,0,1
1,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,...,1.0,0.0,0,0,0,0,50,False,0,1
2,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,286,...,1.0,0.0,1,0,0,0,45,True,1,1
3,2016-17,Adam Lallana,MID,NaN,1,2,33,0,33.7,205,...,3.0,57.0,11,0,0,0,70,False,1,1
4,2016-17,Adrián San Miguel del Castillo,GK,NaN,0,0,16,0,0.0,450,...,2.0,0.0,2,0,0,0,50,False,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1692,2021-22,Wilfred Ndidi,MID,Leicester,0,0,13,0,2.0,216,...,1.0,2.0,2,-7608,9581,17189,50,False,0,3
1693,2021-22,Matt Ritchie,DEF,Newcastle,0,0,12,0,11.3,292,...,2.0,4.0,1,208,4934,4726,50,True,0,3
1694,2021-22,Nathan Redmond,MID,Southampton,0,0,4,0,23.3,336,...,2.0,0.0,1,-1164,403,1567,59,False,0,3
1695,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,65,...,0.0,0.0,0,-134,0,134,45,True,0,3
1696,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,415,...,2.0,0.0,0,-996,582,1578,45,True,0,3

### selecting the last three season

In [21]:
result.reset_index(inplace=True)

In [22]:
df = result.drop('index',axis = 1)

In [23]:
df

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,...,2.0,0.0,0,0,0,0,55,False,0,1
1,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,...,1.0,0.0,0,0,0,0,50,False,0,1
2,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,286,...,1.0,0.0,1,0,0,0,45,True,1,1
3,2016-17,Adam Lallana,MID,NaN,1,2,33,0,33.7,205,...,3.0,57.0,11,0,0,0,70,False,1,1
4,2016-17,Adrián San Miguel del Castillo,GK,NaN,0,0,16,0,0.0,450,...,2.0,0.0,2,0,0,0,50,False,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70716,2021-22,Wilfred Ndidi,MID,Leicester,0,0,13,0,2.0,216,...,1.0,2.0,2,-7608,9581,17189,50,False,0,3
70717,2021-22,Matt Ritchie,DEF,Newcastle,0,0,12,0,11.3,292,...,2.0,4.0,1,208,4934,4726,50,True,0,3
70718,2021-22,Nathan Redmond,MID,Southampton,0,0,4,0,23.3,336,...,2.0,0.0,1,-1164,403,1567,59,False,0,3
70719,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,65,...,0.0,0.0,0,-134,0,134,45,True,0,3
70720,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,415,...,2.0,0.0,0,-996,582,1578,45,True,0,3

In [24]:
df = df[df.season_x != '2016-17']

In [25]:
df = df[df.season_x != '2017-18']

In [26]:
df

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
16848,2018-19,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,402,...,4.0,0.0,0,0,0,0,55,False,0,1
16849,2018-19,Aaron Mooy,MID,NaN,0,0,24,0,18.2,199,...,0.0,0.0,2,0,0,0,55,True,0,1
16850,2018-19,Aaron Wan-Bissaka,DEF,NaN,1,3,38,1,14.0,145,...,0.0,0.0,12,0,0,0,40,False,0,1
16851,2018-19,Abdoulaye Doucouré,MID,NaN,0,0,16,1,25.8,390,...,2.0,2.0,3,0,0,0,60,True,0,1
16852,2018-19,Aboubakar Kamara,MID,NaN,0,0,2,0,25.6,189,...,0.0,22.0,1,0,0,0,45,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70716,2021-22,Wilfred Ndidi,MID,Leicester,0,0,13,0,2.0,216,...,1.0,2.0,2,-7608,9581,17189,50,False,0,3
70717,2021-22,Matt Ritchie,DEF,Newcastle,0,0,12,0,11.3,292,...,2.0,4.0,1,208,4934,4726,50,True,0,3
70718,2021-22,Nathan Redmond,MID,Southampton,0,0,4,0,23.3,336,...,2.0,0.0,1,-1164,403,1567,59,False,0,3
70719,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,65,...,0.0,0.0,0,-134,0,134,45,True,0,3
70720,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,415,...,2.0,0.0,0,-996,582,1578,45,True,0,3

In [27]:
df.reset_index(inplace=True)

In [28]:
df

,index,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,16848,2018-19,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,...,4.0,0.0,0,0,0,0,55,False,0,1
1,16849,2018-19,Aaron Mooy,MID,NaN,0,0,24,0,18.2,...,0.0,0.0,2,0,0,0,55,True,0,1
2,16850,2018-19,Aaron Wan-Bissaka,DEF,NaN,1,3,38,1,14.0,...,0.0,0.0,12,0,0,0,40,False,0,1
3,16851,2018-19,Abdoulaye Doucouré,MID,NaN,0,0,16,1,25.8,...,2.0,2.0,3,0,0,0,60,True,0,1
4,16852,2018-19,Aboubakar Kamara,MID,NaN,0,0,2,0,25.6,...,0.0,22.0,1,0,0,0,45,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53868,70716,2021-22,Wilfred Ndidi,MID,Leicester,0,0,13,0,2.0,...,1.0,2.0,2,-7608,9581,17189,50,False,0,3
53869,70717,2021-22,Matt Ritchie,DEF,Newcastle,0,0,12,0,11.3,...,2.0,4.0,1,208,4934,4726,50,True,0,3
53870,70718,2021-22,Nathan Redmond,MID,Southampton,0,0,4,0,23.3,...,2.0,0.0,1,-1164,403,1567,59,False,0,3
53871,70719,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,...,0.0,0.0,0,-134,0,134,45,True,0,3
53872,70720,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,...,2.0,0.0,0,-996,582,1578,45,True,0,3

In [29]:
df = df.drop('index',axis = 1)

In [30]:
df

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2018-19,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,402,...,4.0,0.0,0,0,0,0,55,False,0,1
1,2018-19,Aaron Mooy,MID,NaN,0,0,24,0,18.2,199,...,0.0,0.0,2,0,0,0,55,True,0,1
2,2018-19,Aaron Wan-Bissaka,DEF,NaN,1,3,38,1,14.0,145,...,0.0,0.0,12,0,0,0,40,False,0,1
3,2018-19,Abdoulaye Doucouré,MID,NaN,0,0,16,1,25.8,390,...,2.0,2.0,3,0,0,0,60,True,0,1
4,2018-19,Aboubakar Kamara,MID,NaN,0,0,2,0,25.6,189,...,0.0,22.0,1,0,0,0,45,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53868,2021-22,Wilfred Ndidi,MID,Leicester,0,0,13,0,2.0,216,...,1.0,2.0,2,-7608,9581,17189,50,False,0,3
53869,2021-22,Matt Ritchie,DEF,Newcastle,0,0,12,0,11.3,292,...,2.0,4.0,1,208,4934,4726,50,True,0,3
53870,2021-22,Nathan Redmond,MID,Southampton,0,0,4,0,23.3,336,...,2.0,0.0,1,-1164,403,1567,59,False,0,3
53871,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,65,...,0.0,0.0,0,-134,0,134,45,True,0,3
53872,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,415,...,2.0,0.0,0,-996,582,1578,45,True,0,3

In [31]:
df.isna().sum()

season_x                 0
name                     0
position                 0
team                 27811
assists                  0
bonus                    0
bps                      0
clean_sheets             0
creativity               0
element                  0
fixture                  0
goals_conceded           0
goals_scored             0
ict_index                0
influence                0
kickoff_time             0
minutes                  0
opponent_team            0
own_goals                0
penalties_missed         0
penalties_saved          0
red_cards                0
round                    0
saves                    0
selected                 0
team_a_score            48
team_h_score            48
threat                   0
total_points             0
transfers_balance        0
transfers_in             0
transfers_out            0
value                    0
was_home                 0
yellow_cards             0
GW                       0
dtype: int64

 ## Train test data

## Separate features and label

select all the data as a train data and the last round as a test data

In [32]:
y = df[['total_points']]
X = df.drop('total_points', axis = 1)

In [33]:
test = X[(X['season_x'] == '2021-22')&(X['GW'] == 3)]

In [34]:
test['name']

53296                      Eric Bailly
53297                     Keinan Davis
53298           Ayotomiwa Dele-Bashiru
53299                James Ward-Prowse
53300    Bruno Miguel Borges Fernandes
                     ...
53868                    Wilfred Ndidi
53869                     Matt Ritchie
53870                   Nathan Redmond
53871                      Mathew Ryan
53872                  Ryan Fredericks
Name: name, Length: 577, dtype: object

In [35]:
X_test = X[(X['season_x'] == '2021-22')&(X['GW'] == 3)]

In [36]:
X_test

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_a_score,team_h_score,threat,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
53296,2021-22,Eric Bailly,DEF,Man Utd,0,0,0,0,0.0,286,...,1.0,0.0,0.0,-509,378,887,50,False,0,3
53297,2021-22,Keinan Davis,FWD,Aston Villa,0,0,0,0,0.0,49,...,1.0,1.0,0.0,-15894,6315,22209,45,True,0,3
53298,2021-22,Ayotomiwa Dele-Bashiru,MID,Watford,0,0,0,0,0.0,394,...,0.0,1.0,0.0,-539,0,539,45,False,0,3
53299,2021-22,James Ward-Prowse,MID,Southampton,0,2,28,0,39.2,341,...,2.0,2.0,34.0,-20809,19441,40250,65,False,1,3
53300,2021-22,Bruno Miguel Borges Fernandes,MID,Man Utd,0,0,4,1,25.8,277,...,1.0,0.0,23.0,-3080,149207,152287,121,False,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53868,2021-22,Wilfred Ndidi,MID,Leicester,0,0,13,0,2.0,216,...,2.0,1.0,2.0,-7608,9581,17189,50,False,0,3
53869,2021-22,Matt Ritchie,DEF,Newcastle,0,0,12,0,11.3,292,...,2.0,2.0,4.0,208,4934,4726,50,True,0,3
53870,2021-22,Nathan Redmond,MID,Southampton,0,0,4,0,23.3,336,...,2.0,2.0,0.0,-1164,403,1567,59,False,0,3
53871,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,65,...,2.0,0.0,0.0,-134,0,134,45,True,0,3
53872,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,415,...,2.0,2.0,0.0,-996,582,1578,45,True,0,3

In [37]:
X_train = X[0:53296][:]

In [38]:
X_train.head()

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,team_a_score,team_h_score,threat,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2018-19,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,402,...,0.0,4.0,0.0,0,0,0,55,False,0,1
1,2018-19,Aaron Mooy,MID,NaN,0,0,24,0,18.2,199,...,3.0,0.0,0.0,0,0,0,55,True,0,1
2,2018-19,Aaron Wan-Bissaka,DEF,NaN,1,3,38,1,14.0,145,...,2.0,0.0,0.0,0,0,0,40,False,0,1
3,2018-19,Abdoulaye Doucouré,MID,NaN,0,0,16,1,25.8,390,...,0.0,2.0,2.0,0,0,0,60,True,0,1
4,2018-19,Aboubakar Kamara,MID,NaN,0,0,2,0,25.6,189,...,2.0,0.0,22.0,0,0,0,45,True,0,1

# dropping column 'kick_off'
X_train.

In [39]:
y_test = y[53296:53873][:]

In [40]:
y_test

       total_points
53296             0
53297             0
53298             0
53299             8
53300             2
...             ...
53868             2
53869             1
53870             1
53871             0
53872             0

[577 rows x 1 columns]

In [41]:
y_train = y[0:53296][:]

In [42]:
y_test

       total_points
53296             0
53297             0
53298             0
53299             8
53300             2
...             ...
53868             2
53869             1
53870             1
53871             0
53872             0

[577 rows x 1 columns]

## explore the data

In [43]:
df_train = pd.concat([X_train, y_train], axis = 1)

In [44]:
X_train.isna().sum()## sns.pairplot(df_train, hue = 'total_points')

season_x                 0
name                     0
position                 0
team                 27811
assists                  0
bonus                    0
bps                      0
clean_sheets             0
creativity               0
element                  0
fixture                  0
goals_conceded           0
goals_scored             0
ict_index                0
influence                0
kickoff_time             0
minutes                  0
opponent_team            0
own_goals                0
penalties_missed         0
penalties_saved          0
red_cards                0
round                    0
saves                    0
selected                 0
team_a_score            48
team_h_score            48
threat                   0
transfers_balance        0
transfers_in             0
transfers_out            0
value                    0
was_home                 0
yellow_cards             0
GW                       0
dtype: int64

In [45]:
df_train.corr()

,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,...,team_h_score,threat,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,total_points
assists,1.000000,0.306422,0.399228,0.125617,0.389806,-0.031976,-0.013359,0.091266,0.112608,0.403467,...,0.080640,0.239942,0.055021,0.133946,0.080438,0.198213,0.010093,0.034328,-0.011618,0.453578
bonus,0.306422,1.000000,0.650321,0.279698,0.291752,-0.045545,-0.010012,0.027733,0.616974,0.535108,...,-0.001425,0.371780,0.061804,0.152425,0.092631,0.188286,0.013090,0.011942,-0.008418,0.753421
bps,0.399228,0.650321,1.000000,0.504836,0.514655,-0.106134,-0.030771,0.323998,0.573683,0.771750,...,0.044680,0.464053,0.105600,0.232231,0.125621,0.239176,0.019924,0.108327,-0.026545,0.908576
clean_sheets,0.125617,0.279698,0.504836,1.000000,0.264330,-0.070501,-0.007253,-0.206165,0.123272,0.334319,...,-0.133303,0.230474,0.079122,0.144467,0.059932,0.156957,0.041897,0.099220,-0.001739,0.582788
creativity,0.389806,0.291752,0.514655,0.264330,1.000000,-0.083250,-0.021933,0.260848,0.208334,0.761316,...,0.020868,0.441583,0.113576,0.245513,0.130177,0.331405,0.037283,0.134423,-0.020718,0.447421
element,-0.031976,-0.045545,-0.106134,-0.070501,-0.083250,1.000000,0.110536,-0.073663,-0.039806,-0.103168,...,0.002942,-0.072362,0.008327,-0.052350,-0.071899,-0.152178,-0.000019,-0.032715,0.098812,-0.092991
fixture,-0.013359,-0.010012,-0.030771,-0.007253,-0.021933,0.110536,1.000000,-0.044017,-0.012855,-0.029625,...,-0.007538,-0.016127,0.013294,-0.043376,-0.068240,-0.058739,0.001817,-0.020010,0.975076,-0.024153
goals_conceded,0.091266,0.027733,0.323998,-0.206165,0.260848,-0.073663,-0.044017,1.000000,0.100518,0.351000,...,0.225108,0.215614,0.047940,0.121714,0.075884,0.093721,-0.043460,0.172094,-0.041693,0.136549
goals_scored,0.112608,0.616974,0.573683,0.123272,0.208334,-0.039806,-0.012855,0.100518,1.000000,0.617170,...,0.085548,0.565809,0.060619,0.172101,0.117017,0.282465,0.012927,0.045976,-0.011267,0.664784
ict_index,0.403467,0.535108,0.771750,0.334319,0.761316,-0.103168,-0.029625,0.351000,0.617170,1.000000,...,0.053516,0.833596,0.136016,0.314190,0.179247,0.426391,0.029978,0.151415,-0.028537,0.751206
influence,0.372397,0.625546,0.899174,0.324044,0.492590,-0.097483,-0.034615,0.383010,0.682675,0.839440,...,0.073156,0.537389,0.097930,0.226857,0.129803,0.250841,0.004573,0.148147,-0.033132,0.829228
minutes,0.208056,0.277952,0.747746,0.445450,0.508470,-0.128608,-0.044956,0.601967,0.217106,0.668251,...,0.010326,0.436755,0.118646,0.254660,0.133893,0.243645,0.001793,0.264808,-0.039599,0.623980
opponent_team,0.003114,0.000902,0.003528,-0.004849,-0.004154,-0.024017,0.004747,0.005091,0.000290,0.000268,...,0.028648,-0.002405,-0.003940,-0.002738,0.002174,0.001195,-0.002448,-0.004817,-0.008033,-0.000910
own_goals,0.007179,-0.005660,0.003679,-0.015715,0.007760,-0.002007,-0.004246,0.078539,0.003975,0.014160,...,0.020985,0.008057,0.008960,0.010335,-0.000188,-0.005491,-0.006245,0.010710,-0.004208,-0.028356
penalties_missed,0.017716,0.020978,0.008256,0.009624,0.041243,-0.011684,-0.004494,0.019388,0.054262,0.075064,...,-0.000678,0.088297,0.010142,0.029839,0.020788,0.053126,-0.010059,0.006102,-0.004494,0.017550
penalties_saved,-0.005387,0.093250,0.071804,0.009300,-0.012135,0.001087,-0.000745,0.021514,-0.005534,0.025395,...,0.002462,-0.011364,-0.002020,0.000705,0.003556,-0.007689,0.009851,-0.003590,-0.001218,0.089275
red_cards,-0.002512,-0.010375,-0.035006,-0.004224,0.007536,-0.008582,-0.008048,0.060796,-0.000054,0.001031,...,0.003321,0.005031,0.009074,0.020326,0.011224,0.003209,-0.010362,-0.011650,-0.007750,-0.051951
round,-0.011618,-0.008418,-0.026545,-0.001739,-0.020718,0.098812,0.975076,-0.041693,-0.011267,-0.028537,...,-0.006355,-0.016001,0.012775,-0.040475,-0.064177,-0.055677,0.000329,-0.018626,1.000000,-0.019303
saves,-0.029997,0.107744,0.225332,0.068088,-0.075095,-0.025759,-0.013226,0.146834,-0.033882,0.059059,...,0.003536,-0.069607,0.009477,0.027097,0.018517,-0.039444,-0.012836,-0.014375,-0.013715,0.161449
selected,0.157667,0.192254,0.305326,0.182069,0.268122,-0.129173,0.005275,0.146807,0.192553,0.361111,...,0.024457,0.317064,0.132623,0.576924,0.488005,0.516727,0.001910,0.047192,0.008707,0.309276
team_a_score,0.076887,-0.002289,0.019392,-0.175889,0.008875,-0.007271,-0.041432,0.205886,0.077838,0.039174,...,-0.144666,0.024006,0.003089,0.010742,0.008231,0.018787,-0.026907,0.001258,-0.042275,-0.015562
team_h_score,0.080640,-0.001425,0.044680,-0.133303,0.020868,0.002942,-0.007538,0.225108,0.085548,0.053516,...,1.000000,0.033698,0.002842,0.015661,0.014235,0.038643,0.029271,-0.012776,-0.006355,0.006994
threat,0.239942,0.371780,0.464053,0.230474,0.441583,-0.072362,-0.016127,0.215614,0.565809,0.833596,...,0.033698,1.000000,0.121137,0.292540,0.174365,0.452042,0.033136,0.092235,-0.016001,0.538085
transfers_balance,0.055021,0.061804,0.105600,0.079122,0.113576,0.008327,0.013294,0.047940,0.060619,0.136016,...,0.002842,0.121137,1.000000,0.694130,-0.552754,0.028907,0.022618,0.025236,0.012775,0.107567
transfers_in,0.133946,0.152425,0.232231,0.144467,0.245513,-0.052350,-0.043376,0.121714,0.172101,0.314190,...,0.015661,0.292540,0.694130,1.000000,0.216199,0.348727,0.017023,0.043898,-0.040475,0.245783
transfers_out,0.080438,0.092631,0.125621,0.059932,0.130177,-0.071899,-0.068240,0.075884,0.117017,0.179247,...,0.014235,0.174365,-0.552754,0.216199,1.000000,0.364506,-0.010966,0.016592,-0.064177,0.138641
value,0.198213,0.188286,0.239176,0.156957,0.331405,-0.152178,-0.058739,0.093721,0.282465,0.426391,...,0.038643,0.452042,0.028907,0.348727,0.364506,1.000000,0.000262,0.032359,-0.055677,0.305984
was_home,0.010093,0.013090,0.019924,0.041897,0.037283,-0.000019,0.001817,-0.043460,0.012927,0.029978,...,0.029271,0.033136,0.022618,0.017023,-0.010966,0.000262,1.000000,-0.009407,0.000329,0.028402
yellow_cards,0.034328,0.011942,0.108327,0.099220,0.134423,-0.032715,-0.020010,0.172094,0.045976,0.151415,...,-0.012776,0.092235,0.025236,0.043898,0.016592,0.032359,-0.009407,1.000000,-0.018626,0.053439
GW,-0.011618,-0.008418,-0.026545,-0.001739,-0.020718,0.098812,0.975076,-0.041693,-0.011267,-0.028537,...,-0.006355,-0.016001,0.012775,-0.040475,-0.064177,-0.055677,0.000329,-0.018626,1.000000,-0.019303
total_points,0.453578,0.753421,0.908576,0.582788,0.447421,-0.092991,-0.024153,0.136549,0.664784,0.751206,...,0.006994,0.538085,0.107567,0.245783,0.138641,0.305984,0.028402,0.053439,-0.019303,1.000000

In [46]:
df_train.corr()['total_points']

assists              0.453578
bonus                0.753421
bps                  0.908576
clean_sheets         0.582788
creativity           0.447421
element             -0.092991
fixture             -0.024153
goals_conceded       0.136549
goals_scored         0.664784
ict_index            0.751206
influence            0.829228
minutes              0.623980
opponent_team       -0.000910
own_goals           -0.028356
penalties_missed     0.017550
penalties_saved      0.089275
red_cards           -0.051951
round               -0.019303
saves                0.161449
selected             0.309276
team_a_score        -0.015562
team_h_score         0.006994
threat               0.538085
transfers_balance    0.107567
transfers_in         0.245783
transfers_out        0.138641
value                0.305984
was_home             0.028402
yellow_cards         0.053439
GW                  -0.019303
total_points         1.000000
Name: total_points, dtype: float64

In [47]:
#X_train=  X_train.drop('own_goals', axis = 1)

In [48]:
#X_train=  X_train.drop('element', axis = 1)

In [49]:
#X_train=  X_train.drop('fixture', axis = 1)

In [50]:
#X_train=  X_train.drop('opponent_team', axis = 1)

In [51]:
#X_train=  X_train.drop('red_cards', axis = 1)

In [52]:
#X_train=  X_train.drop('round', axis = 1)

In [53]:
X_train=  X_train.drop('kickoff_time', axis = 1)

In [54]:
X_train=  X_train.drop('team', axis = 1)

In [55]:
X_train=  X_train.drop('name', axis = 1)

In [56]:
X_train.columns

Index(['season_x', 'position', 'assists', 'bonus', 'bps', 'clean_sheets',
       'creativity', 'element', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'minutes', 'opponent_team', 'own_goals',
       'penalties_missed', 'penalties_saved', 'red_cards', 'round', 'saves',
       'selected', 'team_a_score', 'team_h_score', 'threat',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [57]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53296 entries, 0 to 53295
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season_x           53296 non-null  object
 1   position           53296 non-null  object
 2   assists            53296 non-null  int64
 3   bonus              53296 non-null  int64
 4   bps                53296 non-null  int64
 5   clean_sheets       53296 non-null  int64
 6   creativity         53296 non-null  float64
 7   element            53296 non-null  int64
 8   fixture            53296 non-null  int64
 9   goals_conceded     53296 non-null  int64
 10  goals_scored       53296 non-null  int64
 11  ict_index          53296 non-null  float64
 12  influence          53296 non-null  float64
 13  minutes            53296 non-null  int64
 14  opponent_team      53296 non-null  int64
 15  own_goals          53296 non-null  int64
 16  penalties_missed   53296 non-null  int64
 17  penalties_saved    53296 non-null  int64
 18  red_cards          53296 non-null  int64
 19  round              53296 non-null  int64
 20  saves              53296 non-null  int64
 21  selected           53296 non-null  int64
 22  team_a_score       53248 non-null  float64
 23  team_h_score       53248 non-null  float64
 24  threat             53296 non-null  float64
 25  transfers_balance  53296 non-null  int64
 26  transfers_in       53296 non-null  int64
 27  transfers_out      53296 non-null  int64
 28  value              53296 non-null  int64
 29  was_home           53296 non-null  bool
 30  yellow_cards       53296 non-null  int64
 31  GW                 53296 non-null  int64
dtypes: bool(1), float64(6), int64(23), object(2)
memory usage: 12.7+ MB

In [58]:
X_train.isna().sum()

season_x              0
position              0
assists               0
bonus                 0
bps                   0
clean_sheets          0
creativity            0
element               0
fixture               0
goals_conceded        0
goals_scored          0
ict_index             0
influence             0
minutes               0
opponent_team         0
own_goals             0
penalties_missed      0
penalties_saved       0
red_cards             0
round                 0
saves                 0
selected              0
team_a_score         48
team_h_score         48
threat                0
transfers_balance     0
transfers_in          0
transfers_out         0
value                 0
was_home              0
yellow_cards          0
GW                    0
dtype: int64

In [59]:
X_train['team_a_score']=X_train['team_a_score'].fillna(X_train['team_a_score'].mean())

In [60]:
X_train['team_h_score']=X_train['team_h_score'].fillna(X_train['team_h_score'].mean())

In [61]:
#X_train=  X_train.drop(['bonus','bps'], axis = 1)

## Feature Engineering on the training data

In [62]:
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [63]:
cat_pipe = make_pipeline(OneHotEncoder(sparse = False))

In [64]:
num_pipe = make_pipeline(StandardScaler())

In [65]:
feature_transform = make_column_transformer(
    (cat_pipe, ['season_x', 'position','was_home']),
    (num_pipe, ['assists','clean_sheets','creativity','element','fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'minutes', 'opponent_team',
       'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards',
       'round', 'saves', 'selected', 'team_a_score', 'team_h_score', 'threat',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value', 'yellow_cards', 'GW'])
)

In [66]:
X_train_transformed = feature_transform.fit_transform(X_train)

In [67]:
X_train_transformed

array([[ 1.        ,  0.        ,  0.        , ...,  0.19913579,
        -0.24731756, -1.6061323 ],
       [ 1.        ,  0.        ,  0.        , ...,  0.19913579,
        -0.24731756, -1.6061323 ],
       [ 1.        ,  0.        ,  0.        , ..., -0.9720685 ,
        -0.24731756, -1.6061323 ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.58953722,
        -0.24731756, -1.52411253],
       [ 0.        ,  0.        ,  0.        , ..., -0.58166707,
        -0.24731756, -1.52411253],
       [ 0.        ,  0.        ,  0.        , ..., -0.58166707,
        -0.24731756, -1.52411253]])

In [68]:
X_test=  X_test.drop('kickoff_time', axis = 1)

In [69]:
X_test=  X_test.drop('name', axis = 1)

X_test_drop=  X_test.drop(['goals_scored', 'goals_conceded','assists',, axis = 1)

In [70]:
X_test=  X_test.drop('team', axis = 1)

In [71]:
X_test.season_x.dtype

dtype('O')

In [72]:
X_test.season_x.unique()

array(['2021-22'], dtype=object)

In [73]:
X_test_transformed = feature_transform.transform(X_test)

## model

run a linear reg. model

In [74]:
from sklearn.linear_model import LinearRegression

In [75]:
lr = LinearRegression()
lr.fit(X_train_transformed, y_train)

LinearRegression()

In [76]:
y_pred = lr.predict(X_train_transformed)

In [77]:
y_pred_2 = lr.predict(X_test_transformed)

In [78]:
round(lr.score(X_train_transformed, y_train),3)

0.907

In [79]:
round(lr.score(X_test_transformed, y_test),3)

0.923

In [80]:
from sklearn.model_selection import cross_val_score

In [81]:
cross_val_score(lr, X_train_transformed, y_train)

array([ 9.03433737e-01,  9.05462544e-01,  9.07334499e-01,  9.05015071e-01,
       -1.71235561e+21])

In [82]:
y_pred

array([[0.14758301],
       [1.66387939],
       [8.79595947],
       ...,
       [0.08514404],
       [0.04040527],
       [0.1696167 ]])

In [83]:
test['prediction'] = y_pred_2

<ipython-input-83-265a596fa121>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['prediction'] = y_pred_2

In [84]:
test['y_test'] = y_test

<ipython-input-84-51cc30352c6e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['y_test'] = y_test

In [85]:
round(test[['name','prediction','y_test']])

                                name  prediction  y_test
53296                    Eric Bailly         0.0       0
53297                   Keinan Davis         0.0       0
53298         Ayotomiwa Dele-Bashiru         0.0       0
53299              James Ward-Prowse         7.0       8
53300  Bruno Miguel Borges Fernandes         3.0       2
...                              ...         ...     ...
53868                  Wilfred Ndidi         2.0       2
53869                   Matt Ritchie         2.0       1
53870                 Nathan Redmond         1.0       1
53871                    Mathew Ryan         0.0       0
53872                Ryan Fredericks         0.0       0

[577 rows x 3 columns]

In [86]:
test['name']

53296                      Eric Bailly
53297                     Keinan Davis
53298           Ayotomiwa Dele-Bashiru
53299                James Ward-Prowse
53300    Bruno Miguel Borges Fernandes
                     ...
53868                    Wilfred Ndidi
53869                     Matt Ritchie
53870                   Nathan Redmond
53871                      Mathew Ryan
53872                  Ryan Fredericks
Name: name, Length: 577, dtype: object

In [87]:
test.sort_values('prediction',ascending=False)

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,threat,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,prediction,y_test
53811,2021-22,Ferran Torres,MID,Man City,1,2,51,1,16.2,268,...,69.0,-8283,23995,32278,70,True,0,3,19.477844,18
53493,2021-22,Conor Gallagher,MID,Crystal Palace,0,3,50,0,24.1,144,...,54.0,373,1048,675,55,False,0,3,13.458313,15
53546,2021-22,Gabriel Fernando de Jesus,FWD,Man City,1,3,53,1,60.7,263,...,39.0,62491,95472,32981,85,True,0,3,13.113770,12
53575,2021-22,Jamie Vardy,FWD,Leicester,1,3,41,0,10.6,205,...,36.0,-106318,77000,183318,105,False,0,3,11.304932,12
53803,2021-22,Michail Antonio,FWD,West Ham,1,2,46,0,48.3,413,...,105.0,1011895,1064559,52664,78,True,0,3,10.396790,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53844,2021-22,Sead Kolasinac,DEF,Arsenal,0,0,3,0,0.0,11,...,0.0,-1098,362,1460,44,False,1,3,-0.335510,-1
53557,2021-22,Aaron Lennon,MID,Burnley,0,0,-2,0,0.5,575,...,0.0,0,0,0,50,True,1,3,-0.559326,0
53823,2021-22,Morgan Gibbs-White,MID,Wolves,0,0,-2,0,0.3,440,...,4.0,-2165,2210,4375,45,True,1,3,-0.628662,0
53310,2021-22,José Diogo Dalot Teixeira,DEF,Man Utd,0,0,0,0,0.0,510,...,0.0,-772,288,1060,45,False,1,3,-0.845276,0
53799,2021-22,Granit Xhaka,MID,Arsenal,0,0,-5,0,0.3,7,...,0.0,-7688,5786,13474,50,False,0,3,-3.564270,-2

make pre for the next match

In [88]:
test.head()

,season_x,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,...,threat,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,prediction,y_test
53296,2021-22,Eric Bailly,DEF,Man Utd,0,0,0,0,0.0,286,...,0.0,-509,378,887,50,False,0,3,0.199768,0
53297,2021-22,Keinan Davis,FWD,Aston Villa,0,0,0,0,0.0,49,...,0.0,-15894,6315,22209,45,True,0,3,0.055847,0
53298,2021-22,Ayotomiwa Dele-Bashiru,MID,Watford,0,0,0,0,0.0,394,...,0.0,-539,0,539,45,False,0,3,0.109741,0
53299,2021-22,James Ward-Prowse,MID,Southampton,0,2,28,0,39.2,341,...,34.0,-20809,19441,40250,65,False,1,3,6.610229,8
53300,2021-22,Bruno Miguel Borges Fernandes,MID,Man Utd,0,0,4,1,25.8,277,...,23.0,-3080,149207,152287,121,False,1,3,3.389160,2

In [89]:
test.to_csv('pred.csv' ,index=False)

In [90]:
X_train.head()

,season_x,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,...,team_a_score,team_h_score,threat,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2018-19,DEF,0,0,0,0,0.0,402,5,0,...,0.0,4.0,0.0,0,0,0,55,False,0,1
1,2018-19,MID,0,0,24,0,18.2,199,4,3,...,3.0,0.0,0.0,0,0,0,55,True,0,1
2,2018-19,DEF,1,3,38,1,14.0,145,3,0,...,2.0,0.0,0.0,0,0,0,40,False,0,1
3,2018-19,MID,0,0,16,1,25.8,390,9,0,...,0.0,2.0,2.0,0,0,0,60,True,0,1
4,2018-19,MID,0,0,2,0,25.6,189,3,1,...,2.0,0.0,22.0,0,0,0,45,True,0,1

In [91]:
X_train.columns

Index(['season_x', 'position', 'assists', 'bonus', 'bps', 'clean_sheets',
       'creativity', 'element', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'minutes', 'opponent_team', 'own_goals',
       'penalties_missed', 'penalties_saved', 'red_cards', 'round', 'saves',
       'selected', 'team_a_score', 'team_h_score', 'threat',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'GW'],
      dtype='object')

features that you know['season_x' ,position ,'creativity','ict_index', 'influence','opponent_team','selected','team_a_score', 'team_h_score',        , 'threat','transfers_balance', , 'value','transfers_in', 'transfers_out','GW'

 'assists', 'clean_sheets','goals_conceded','goals_scored','minutes','own_goals','penalties_missed', 'penalties_saved','red_cards','saves','yellow_cards',

 'element', 'fixture''round''was_home'

In [92]:
#df_train.groupby('name')['goals_scored'].mean().to_frame().loc['Aaron Connolly','goals_scored']

In [93]:
#df_train.loc[df_train['name']== 'Mohamed Salah']

In [94]:
#test.loc[test['name']== 'Mohamed Salah']

In [95]:
#X_pred_test = test.loc[test['name']== 'Mohamed Salah']

In [96]:
#X_pred_test['goals_scored']= df_train.groupby('name')['goals_scored'].mean().to_frame().loc['Mohamed Salah','goals_scored']

In [97]:
#X_pred_test=  X_pred_test.drop(['kickoff_time','name','team','bonus','bps','prediction', 'y_test'], axis = 1)

In [98]:
#X_pred_test.columns

In [99]:
#X_pred_test_transform=feature_transform.transform(X_pred_test)

In [100]:
#X_test_transformed = feature_transform.transform(X_test)

## save the model